### ISSUE TITLE
Realizer + TMDB Helper based library error

### ISSUE THREAD

**Issue by mosley93** [aenemapy/aenemapyrepo#20]
I've setup library with TMDB Helber addon, added Realizer player to the TMDB Helper.
To watch movies I click item in library, which starts TMDB Helper dialog with players to choose.
After chosing Realizer, it scraps the cloud and present files to play, but after selecting a file nothing ever happens.
The same  item works perfectly fine through the addon.
Here is part of the log:
2020-11-12 13:20:11.368 T:11269  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player.players -- successfully resolved dummy file
                                            /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/dummy.mp4
2020-11-12 13:20:11.369 T:11269  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player - finished executing action
                                            RunScript(plugin.video.themoviedb.helper,run_plugin=plugin://plugin.video.realizer/?action=play&amp;title=Burning+Man&amp;year=2005&amp;imdb=tt0212671&amp;tvdb=130304&amp;season=7&amp;episode=1&amp;tvshowtitle=+&amp;premiered=2005-09-30&amp;meta=%7B%22rating%22%3A%20+%2C%20%22code%22%3A+%22tt0212671%22%2C+%22tmdb%22%3A+2004%2C+%22imdb%22%3A+%22tt0212671%22%2C+%22year%22%3A+%222005%22%2C+%22duration%22%3A+%22+%22%2C+%22plot%22%3A+%22The family attends the counterculture Burning Man festival in the desert.%22%2C+%22votes%22%3A+%22%22%2C+%22thumb%22%3A+%22https://image.tmdb.org/t/p/original/5vEJKebWfCAnappMCQkBkcMwrCS.jpg%22%2C+%22title%22%3A+%22Burning+Man%22%2C+%22tvdb%22%3A+%22130304%22%2C+%22label%22%3A+%22Burning+Man%22%2C+%22season%22%3A+%227%22%2C+%22status%22%3A%20%22+%22%2C%20%22poster%22%3A+%22https://image.tmdb.org/t/p/w500/uwslHj6nEyPX5IbNXhuEeI0PTth.jpg%22%2C+%22tvshowtitle%22%3A+%22+%22%2C+%22mediatype%22%3A+%22episode%22%2C+%22studio%22%3A%20%22+%22%2C%20%22mpaa%22%3A%20%22+%22%2C%20%22genre%22%3A%20%5B%22+%22%5D%2C%20%22votes%22%3A%20+%2C%20%22banner%22%3A+%22https://image.tmdb.org/t/p/original/5vEJKebWfCAnappMCQkBkcMwrCS.jpg%22%2C+%22episode%22%3A+%221%22%2C+%22premiered%22%3A+%222005-09-30%22%2C+%22fanart%22%3A+%22https://image.tmdb.org/t/p/original/5Nrh0PtHuU41f6F8m5WbGm2iEQa.jpg%22%2C+%22trailer%22%3A+%22plugin%3A%2F%2Fplugin.video.realizer%2F%3Faction%3Dtrailer%26name%3D+%22%7D&amp;t=20201112131947821808)
2020-11-12 13:20:13.176 T:11295  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.script.router - attempting to play
                                            plugin://plugin.video.realizer/?action=play&amp;title=Burning+Man&amp;year=2005&amp;imdb=tt0212671&amp;tvdb=130304&amp;season=7&amp;episode=1&amp;tvshowtitle=+&amp;premiered=2005-09-30&amp;meta=%7B%22rating%22%3A%20+%2C%20%22code%22%3A+%22tt0212671%22%2C+%22tmdb%22%3A+2004%2C+%22imdb%22%3A+%22tt0212671%22%2C+%22year%22%3A+%222005%22%2C+%22duration%22%3A+%22+%22%2C+%22plot%22%3A+%22The family attends the counterculture Burning Man festival in the desert.%22%2C+%22votes%22%3A+%22%22%2C+%22thumb%22%3A+%22https://image.tmdb.org/t/p/original/5vEJKebWfCAnappMCQkBkcMwrCS.jpg%22%2C+%22title%22%3A+%22Burning+Man%22%2C+%22tvdb%22%3A+%22130304%22%2C+%22label%22%3A+%22Burning+Man%22%2C+%22season%22%3A+%227%22%2C+%22status%22%3A%20%22+%22%2C%20%22poster%22%3A+%22https://image.tmdb.org/t/p/w500/uwslHj6nEyPX5IbNXhuEeI0PTth.jpg%22%2C+%22tvshowtitle%22%3A+%22+%22%2C+%22mediatype%22%3A+%22episode%22%2C+%22studio%22%3A%20%22+%22%2C%20%22mpaa%22%3A%20%22+%22%2C%20%22genre%22%3A%20%5B%22+%22%5D%2C%20%22votes%22%3A%20+%2C%20%22banner%22%3A+%22https://image.tmdb.org/t/p/original/5vEJKebWfCAnappMCQkBkcMwrCS.jpg%22%2C+%22episode%22%3A+%221%22%2C+%22premiered%22%3A+%222005-09-30%22%2C+%22fanart%22%3A+%22https://image.tmdb.org/t/p/original/5Nrh0PtHuU41f6F8m5WbGm2iEQa.jpg%22%2C+%22trailer%22%3A+%22plugin%3A%2F%2Fplugin.video.realizer%2F%3Faction%3Dtrailer%26name%3D+%22%7D&amp;t=20201112131947821808
2020-11-12 13:20:45.470 T:11465  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.container.router - Attempting to play item
                                            {u'info': u'play', 'tmdb_type': 'tv', u'episode': u'1', u'islocal': u'True', u'tmdb_id': u'2004', u'season': u'7'}
2020-11-12 13:21:01.624 T:11465  NOTICE: [plugin.video.themoviedb.helper]
                                            lib.player - finished resolving path to url
                                            plugin://plugin.video.realizer/?action=play&amp;title=Burning+Man&amp;year=2005&amp;imdb=tt0212671&amp;tvdb=130304&amp;season=7&amp;episode=1&amp;tvshowtitle=+&amp;premiered=2005-09-30&amp;meta=%7B%22rating%22%3A%20+%2C%20%22code%22%3A+%22tt0212671%22%2C+%22tmdb%22%3A+2004%2C+%22imdb%22%3A+%22tt0212671%22%2C+%22year%22%3A+%222005%22%2C+%22duration%22%3A+%22+%22%2C+%22plot%22%3A+%22The family attends the counterculture Burning Man festival in the desert.%22%2C+%22votes%22%3A+%22%22%2C+%22thumb%22%3A+%22https://image.tmdb.org/t/p/original/5vEJKebWfCAnappMCQkBkcMwrCS.jpg%22%2C+%22title%22%3A+%22Burning+Man%22%2C+%22tvdb%22%3A+%22130304%22%2C+%22label%22%3A+%22Burning+Man%22%2C+%22season%22%3A+%227%22%2C+%22status%22%3A%20%22+%22%2C%20%22poster%22%3A+%22https://image.tmdb.org/t/p/w500/uwslHj6nEyPX5IbNXhuEeI0PTth.jpg%22%2C+%22tvshowtitle%22%3A+%22+%22%2C+%22mediatype%22%3A+%22episode%22%2C+%22studio%22%3A%20%22+%22%2C%20%22mpaa%22%3A%20%22+%22%2C%20%22genre%22%3A%20%5B%22+%22%5D%2C%20%22votes%22%3A%20+%2C%20%22banner%22%3A+%22https://image.tmdb.org/t/p/original/5vEJKebWfCAnappMCQkBkcMwrCS.jpg%22%2C+%22episode%22%3A+%221%22%2C+%22premiered%22%3A+%222005-09-30%22%2C+%22fanart%22%3A+%22https://image.tmdb.org/t/p/original/5Nrh0PtHuU41f6F8m5WbGm2iEQa.jpg%22%2C+%22trailer%22%3A+%22plugin%3A%2F%2Fplugin.video.realizer%2F%3Faction%3Dtrailer%26name%3D+%22%7D&amp;t=20201112132045660805
2020-11-12 13:21:20.272 T:11078   ERROR: Playlist Player: skipping unplayable item: 0, path [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/tvshows/Malcolm in the Middle/Season 7/S07E01 - Burning Man.strm]

**Comment by peno64** [comment]
I afraid there is no point in adapting this addon because it uses tmdb to find its movies/shows. And tmdb becomes payed in march and removes the old api that many addons use. So it won't work anymore after march anyway...

**Comment by mosley93** [comment]
I think you're mistaken - TMDB will remain to be free, the TVDB is going to be paid.

**Comment by peno64** [comment]
@mosley93 Unfortunately, realizer also uses tvdb. Just looked in the sources.
