### ISSUE TITLE
script.ezmaintenanceplus Kodi 19

### ISSUE THREAD

**Issue by Janasek** [aenemapy/aenemapyrepo#21]
Hi.

Can you add support for Kodi 19
I care most **about script.ezmaintenanceplus**

thanks....!

**Comment by peno64** [comment]
@Janasek 
Since it has been 2 years that any code change was done and there is almost no answer to issues here, I am a bit afraid for changes for kodi 19 (Matrix)...

However that said, I have been working on it and I have already a working version for Matrix, even with a number of small improvements. The only thing I haven't done yet is complete reset and the wizard all other things work.
Soon I will post here a link where a Matrix version can be downloaded.

**Comment by peno64** [comment]
@aenemapy 
@thisischrys 
@henryjfry

Is there a way I can put the changed code here? Otherewise I will clone the repo and put my changes under my name.

**Comment by Janasek** [comment]
Good news!

complete reset is the option I least care about, I do it with putty if I need to
Any chance of pre-rlease?

**Comment by peno64** [comment]
Tonight I will have a first version. For the wizard, I have to find a way to execute this somehow because I never ever use builds and that is where it is used for as I understand it.

**Comment by peno64** [comment]
@Janasek 

Ok, a first version of EZ Maintenance+ for Matrix (Kodi 19) is available.

Note that this version *only* works on this new kodi version, not on Leia (Kodi 18) or older. Maybe I will adapt it later that it also works for those versions.
All functionality seems to work.

See https://peno64.github.io/ for installation instructions and then you must of course choose to install EZ Maintenance+

Looking foreward to your testing.

**Comment by Janasek** [comment]
Hi.

thanks for your time
Maybe we'll move to your github?

error log:
https://paste.kodi.tv/vodaveyuvi

**Comment by peno64** [comment]
@Janasek 

An update is available on https://peno64.github.io/

It should fix your problem.

This version is now also for both Kodi 18 and 19.

I asked the question to the original developers here if my changes can be put here but I haven't had any response until now.
If it keeps silent I will make a clone and put it on my github.

**Comment by BlackGlassSkin** [comment]
**One more opction for settings,thus it cannot be changed to default**

```
<category label="Backup/Restore">
	<setting id="download.path" type="folder" label="Backup Location" visible="True" />
	<setting id="restore.path" type="folder" label="Restore from Zip Location (folder)" visible="True" />
</category>

```
**now it will be possible to delete the location**
```
<category label="Backup/Restore">
	<setting id="download.path" type="folder" label="Backup Location" default="special://" visible="True" />
	<setting id="restore.path" type="folder" label="Restore from Zip Location (folder)" default="special://" visible="True" />
</category>
```


**it would be good if you could delete older backup versions**

**Comment by peno64** [comment]
@BlackGlassSkin 

I don't see the advantage of having special:// as default there. When you do that and immediately go to backup you get an error because it does not know what to do with special://

**Comment by BlackGlassSkin** [comment]
"special: //" is an example

go to the plugin settings set the backup location, and then press the default settings of the backup location, it cannot be deleted

**Comment by peno64** [comment]
So what is exactly your question? If you press default settings that the backup and restore locations are not changed?

**Comment by BlackGlassSkin** [comment]
"If you press default settings that the backup and restore locations are not changed?"

exactly,

if it's not a problem to add it, ' default=" " ' with space in ""

**Comment by peno64** [comment]
That is against kodi standards and would be a case you only want according to me

**Comment by BlackGlassSkin** [comment]
ok, never mind thanks for the fix
