### ISSUE TITLE
Realizer Real Debrid cloud manager

### ISSUE THREAD

**Issue by sahuja78** [aenemapy/aenemapyrepo#23]
In realizer addon i use the real debrid addon. The torrent file folder is no longer accessible. Please check
as the addon may need an update. Thanks

**Comment by peno64** [comment]
I afraid there is no point in adapting this addon because it uses tmdb to find its movies/shows. And tmdb becomes payed in march and removes the old api that many addons use. So it won't work anymore after march anyway...

**Comment by sahuja78** [comment]
Will the real debrid part work in realizer or it will become useless in March ? Thanks


Thanks

**Comment by peno64** [comment]
No idea.

**Comment by aenemapy** [comment]
The cloud browser will always work, as long as realdebrid provies an api... you can keep using it.
Cheers

**Comment by sahuja78** [comment]
Thank you
