### ISSUE TITLE
Realizer Not Working in Kodi 19

### ISSUE THREAD

**Issue by ghussey1949** [aenemapy/aenemapyrepo#24]
In kodi 19 Realizer addon erroring.  In Dependencies get error for Not available for script.module.metalibrary. Android version.

**Comment by peno64** [comment]
I afraid there is no point in adapting this addon because it uses tmdb to find its movies/shows. And tmdb becomes payed in march and removes the old api that many addons use. So it won't work anymore after march anyway...

**Comment by aenemapy** [comment]
please check new release, cheers
