### ISSUE TITLE
kodi 19

### ISSUE THREAD

**Issue by sahuja78** [aenemapy/aenemapyrepo#25]
Will plan to update repo/app for kodi 19?

**Comment by peno64** [comment]
See #22 for EZ Maintenance+ only. I also tried to contact the developers here but they just don't react.

**Comment by sahuja78** [comment]
> 
> 
> See #22 for EZ Maintenance+ only. I also tried to contact the developers here but they just don't react.

Thank you

**Comment by aenemapy** [comment]
sorry but life has been busy and I did not have time to maintain addons in while. Would you like to maintain the ez maintenace addon? It's ok to me, let me know or I can just update from your fork.

**Comment by sahuja78** [comment]
Thank you

**Comment by sahuja78** [comment]
Update the fork and let me fork. Let me know once done.
I get it with the busy stuff and appreciate your work.
Thank you

**Comment by sahuja78** [comment]
i meant update the fork and let me know. Thank you
