### ISSUE TITLE
Resolver should order items alphabetically 

### ISSUE THREAD

**Issue by AisenT** [aenemapy/aenemapyrepo#3]
When navigating a torrent or download list, the items should be displayed in alphabetical order.

![order](https://user-images.githubusercontent.com/47010059/51705026-a3ff8980-2001-11e9-939d-28a0ac061301.jpg)

Tested in Kodi Krypton.

**Comment by AisenT** [comment]
I tested again after update 2019.01.27.5, but the items aren't ordered. I marked the option to sort torrents alphabetically.

![order2](https://user-images.githubusercontent.com/47010059/51862558-01f3e000-2326-11e9-8de9-ff9d6f6a6724.jpg)

**Comment by AisenT** [comment]
I shouldn't have closed it.

**Comment by aenemapy** [comment]
Issue has been resolved on latest 2019.02.06.2 Version

**Comment by aenemapy** [comment]
Downloads and torrent list are keep as they are to put recently added items first. There is an option in the addon settings to sort the lists alphabetically.
Torrent contents are automatically sorted alphabetically.
