### ISSUE TITLE
change xbmc.translatePath to use xbmcvfs.translatePath for Kodi 20

### ISSUE THREAD

**Issue by garikaib** [aenemapy/aenemapyrepo#34]
This plugin makes use of e xbmc.translatePath which was deprecated in Kodi 19 and is no longer available in the upcoming Kodi 20 it needs to use xbmcvfs.translatePath instead otherwise it will not work with Kodi 20. Current the following error is thrown when on Kodi 20 RC1

`2022-12-31 06:13:41.863 T:7435    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.realizerx/service.py", line 3, in <module>
                                                       from resources.lib.modules import control
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.realizerx/resources/lib/modules/control.py", line 95, in <module>
                                                       transPath = xbmc.translatePath
                                                                   ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
`

**Comment by LoganWolverineX** [comment]
Kodi 20 stable has been released on their website and playstore.  hopefully dev can update realizer and premiumizer asap, so it can work again.

**Comment by LoganWolverineX** [comment]
@aenemapy

**Comment by peno64** [comment]
I created a pull request with the needed changes for kodi 20
I also attach the modified zip files of the 2 addons which can be installed in both kodi 19 and 20

[plugin.video.realizerx.zip](https://github.com/aenemapy/aenemapyrepo/files/10429552/plugin.video.realizerx.zip)
[plugin.video.premiumizerx.zip](https://github.com/aenemapy/aenemapyrepo/files/10429554/plugin.video.premiumizerx.zip)

**Comment by LoganWolverineX** [comment]
@peno64 thank you so much! you are always a life saver when a new kodi version comes out :-)
