### ISSUE TITLE
OpenSubtitles not working with Realizer

### ISSUE THREAD

**Issue by AisenT** [aenemapy/aenemapyrepo#7]
I'm unable to load subtitles in Realizer. When I try to download one, OpenSubtitles returns no matches.

The OpenSubtitles addon is working in Seren and Gaia.

**Comment by iriesound** [comment]
Same issue here. Tried several subtitle addons, but no one is working with Realizer.

**Comment by aenemapy** [comment]
Sorry for the late reply... the issue has been fixed on new release
