### ISSUE TITLE
Crash to desktop with cloud videos.

### ISSUE THREAD

**Issue by roboserg** [aenemapy/aenemapyrepo#8]
Kodi works with local files, but when using the latest premiumizer v2019.04.12 I get CTD when clicking on any video on my premiumize cloud. 

Log - https://pastebin.com/c170jjGp
System - Win 10 64 bit Eng.
Latest 18.2 kodi, latest plug in. Reinstalled Kodi just now.

**Comment by aenemapy** [comment]
Sorry but this appears to be a kodi 18.2 issue, not addon related.

**Comment by roboserg** [comment]
I had the same issue on 18.1. What Kodi version is the plugin stable?

**Comment by aenemapy** [comment]
it's not really a plugin issue but rather some compatibility issues with your setup, I know that the new version of urllib3 shipped with kodi might get some issues too. I would try using a different kodi distro like spmc or going back to a less recent kodi version like 17.6. It might help you out also to clean everything and start from scratch
